import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Badge } from "@/components/ui/badge";
import { Plus, RefreshCw, Gauge, AlertCircle } from "lucide-react";
import { toast } from "sonner";
import { useAuth } from "@/lib/auth";
import { supabase } from "@/lib/supabase";

export const Route = createFileRoute("/meters")({ head: () => ({ meta: [{ title: "العدادات — ميزان" }] }), component: MetersPage });

type Customer = { id: string; name: string };
type Profile = { id: string; name: string; display_type: string; integer_digits: number; decimal_digits: number };
type Meter = { id: string; customer_id: string; profile_id: string | null; serial_number: string; status: string; created_at: string };

function MetersPage() {
  const { user } = useAuth(); const [customers, setCustomers] = useState<Customer[]>([]); const [profiles, setProfiles] = useState<Profile[]>([]); const [meters, setMeters] = useState<Meter[]>([]); const [busy, setBusy] = useState(false);
  const [profileName, setProfileName] = useState(""); const [displayType, setDisplayType] = useState("digital"); const [integerDigits, setIntegerDigits] = useState("5"); const [decimalDigits, setDecimalDigits] = useState("0");
  const [customerId, setCustomerId] = useState(""); const [profileId, setProfileId] = useState(""); const [serial, setSerial] = useState("");
  async function load() { if (!user?.tenantId) return; const [c,p,m] = await Promise.all([supabase.from("customers").select("id,name").eq("tenant_id",user.tenantId).eq("status","active").order("name"),supabase.from("meter_profiles").select("id,name,display_type,integer_digits,decimal_digits").eq("tenant_id",user.tenantId).order("name"),supabase.from("meters").select("id,customer_id,profile_id,serial_number,status,created_at").eq("tenant_id",user.tenantId).order("created_at",{ascending:false})]); const error=[c,p,m].find(x=>x.error)?.error; if(error) throw error; setCustomers((c.data??[]) as Customer[]); setProfiles((p.data??[]) as Profile[]); setMeters((m.data??[]) as Meter[]); }
  useEffect(()=>{ void load().catch(e=>toast.error(`تعذر تحميل العدادات: ${e.message}`)); },[user?.tenantId]);
  async function createProfile(){ const i=Number(integerDigits), d=Number(decimalDigits); if(!profileName.trim()) return toast.error("اسم نوع العداد مطلوب"); if(!Number.isInteger(i)||i<0||i>12||!Number.isInteger(d)||d<0||d>6) return toast.error("عدد الخانات غير صالح"); setBusy(true); try{ const {error}=await supabase.rpc("create_meter_profile",{p_name:profileName.trim(),p_display_type:displayType,p_integer_digits:i,p_decimal_digits:d,p_register_order:"integer_then_decimal",p_color_semantics:{}}); if(error) throw error; toast.success("تم حفظ مواصفات نوع العداد"); setProfileName(""); await load(); }catch(e){toast.error(`فشل حفظ النوع: ${(e as Error).message}`)}finally{setBusy(false)} }
  async function createMeter(){ if(!customerId||!profileId||!serial.trim()) return toast.error("المشترك ونوع العداد ورقم العداد مطلوبة"); setBusy(true); try{const {error}=await supabase.rpc("create_meter",{p_customer_id:customerId,p_serial_number:serial.trim(),p_profile_id:profileId}); if(error) throw error; toast.success("تم تسجيل العداد الحقيقي وتفعيله"); setSerial(""); await load();}catch(e){toast.error(`فشل تسجيل العداد: ${(e as Error).message}`)}finally{setBusy(false)} }
  async function deactivate(id:string){ if(!window.confirm("تأكيد إيقاف هذا العداد؟ لن تُحذف القراءات السابقة.")) return; setBusy(true); try{const {error}=await supabase.rpc("deactivate_meter",{p_meter_id:id}); if(error) throw error; toast.success("تم إيقاف العداد"); await load();}catch(e){toast.error(`فشل الإيقاف: ${(e as Error).message}`)}finally{setBusy(false)} }
  return <div className="space-y-6" dir="rtl"><div className="flex items-start justify-between"><div><h1 className="text-2xl md:text-3xl font-bold">العدادات</h1><p className="text-sm text-muted-foreground mt-1">المصدر التشغيلي الوحيد للعدادات هو قاعدة البيانات؛ لا يتم إنشاء بيانات تجريبية.</p></div><Button size="sm" variant="outline" onClick={()=>void load()}><RefreshCw className="w-4 h-4 ms-1"/> تحديث</Button></div>
    {meters.length===0&&<div className="rounded-lg border border-amber-300 bg-amber-50 p-4 text-sm text-amber-900 flex gap-2"><AlertCircle className="w-5 h-5"/> لا توجد عدادات حالية. بعد إدخال المواصفات والعدادات الحقيقية يمكن بدء القراءة الميدانية.</div>}
    <div className="grid gap-4 lg:grid-cols-2"><Card><CardHeader><CardTitle>تعريف نوع عداد</CardTitle></CardHeader><CardContent className="space-y-3"><div><Label>اسم النوع</Label><Input value={profileName} onChange={e=>setProfileName(e.target.value)} placeholder="مثلاً: عداد 5 صحيح + 2 عشري"/></div><div><Label>نوع العرض</Label><Select value={displayType} onValueChange={setDisplayType}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{["digital","mechanical","analog","circular","hybrid"].map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select></div><div className="grid grid-cols-2 gap-3"><div><Label>الخانات الصحيحة</Label><Input type="number" min="0" max="12" value={integerDigits} onChange={e=>setIntegerDigits(e.target.value)}/></div><div><Label>الخانات العشرية</Label><Input type="number" min="0" max="6" value={decimalDigits} onChange={e=>setDecimalDigits(e.target.value)}/></div></div><p className="text-xs text-muted-foreground">هذا التعريف هو الذي يحدد قبول الكسور. لا يتم استنتاج المنازل العشرية من لون الصورة أو من OCR.</p><Button onClick={()=>void createProfile()} disabled={busy}><Plus className="w-4 h-4 ms-1"/> حفظ النوع</Button></CardContent></Card>
    <Card><CardHeader><CardTitle>تسجيل عداد حقيقي</CardTitle></CardHeader><CardContent className="space-y-3"><div><Label>المشترك</Label><Select value={customerId} onValueChange={setCustomerId}><SelectTrigger><SelectValue placeholder="اختر المشترك"/></SelectTrigger><SelectContent>{customers.map(c=><SelectItem key={c.id} value={c.id}>{c.name}</SelectItem>)}</SelectContent></Select></div><div><Label>مواصفات العداد</Label><Select value={profileId} onValueChange={setProfileId}><SelectTrigger><SelectValue placeholder="اختر النوع"/></SelectTrigger><SelectContent>{profiles.map(p=><SelectItem key={p.id} value={p.id}>{p.name} · {p.integer_digits} صحيح / {p.decimal_digits} عشري</SelectItem>)}</SelectContent></Select></div><div><Label>رقم العداد الفعلي</Label><Input value={serial} onChange={e=>setSerial(e.target.value)} placeholder="الرقم المطبوع على العداد"/></div><Button onClick={()=>void createMeter()} disabled={busy||!profiles.length||!customers.length}><Gauge className="w-4 h-4 ms-1"/> تسجيل وتفعيل</Button>{!profiles.length&&<p className="text-xs text-destructive">أنشئ مواصفة نوع العداد أولاً؛ لا يمكن إنشاء عداد بلا مواصفة.</p>}</CardContent></Card></div>
    <Card><CardHeader><CardTitle>العدادات المسجلة ({meters.length})</CardTitle></CardHeader><CardContent className="overflow-auto"><table className="w-full text-sm"><thead><tr className="border-b text-right"><th className="p-2">العداد</th><th className="p-2">المشترك</th><th className="p-2">المواصفة</th><th className="p-2">الحالة</th><th className="p-2"></th></tr></thead><tbody>{meters.map(m=>{const c=customers.find(x=>x.id===m.customer_id);const p=profiles.find(x=>x.id===m.profile_id);return <tr key={m.id} className="border-b"><td className="p-2 font-mono">{m.serial_number}</td><td className="p-2">{c?.name??"—"}</td><td className="p-2">{p?`${p.integer_digits} صحيح / ${p.decimal_digits} عشري`:"غير محدد"}</td><td className="p-2"><Badge variant={m.status==="active"?"default":"secondary"}>{m.status==="active"?"فعّال":"موقوف"}</Badge></td><td className="p-2">{m.status==="active"&&<Button size="sm" variant="outline" onClick={()=>void deactivate(m.id)} disabled={busy}>إيقاف</Button>}</td></tr>})}</tbody></table></CardContent></Card>
  </div>;
}
