/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubscriptionRouteImport } from './routes/subscription'
import { Route as ReadingsRouteImport } from './routes/readings'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as LossAnalysisRouteImport } from './routes/loss-analysis'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as BillsRouteImport } from './routes/bills'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuperAdminIndexRouteImport } from './routes/super-admin/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as MetersRouteImport } from './routes/meters'
import { Route as TariffsRouteImport } from './routes/tariffs'
import { Route as UpdatePasswordRouteImport } from './routes/update-password'

const SubscriptionRoute = SubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadingsRoute = ReadingsRouteImport.update({
  id: '/readings',
  path: '/readings',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const LossAnalysisRoute = LossAnalysisRouteImport.update({
  id: '/loss-analysis',
  path: '/loss-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const BillsRoute = BillsRouteImport.update({
  id: '/bills',
  path: '/bills',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({ id: '/account', path: '/account', getParentRoute: () => rootRouteImport } as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({ id: '/forgot-password', path: '/forgot-password', getParentRoute: () => rootRouteImport } as any)
const MetersRoute = MetersRouteImport.update({ id: '/meters', path: '/meters', getParentRoute: () => rootRouteImport } as any)
const TariffsRoute = TariffsRouteImport.update({ id: '/tariffs', path: '/tariffs', getParentRoute: () => rootRouteImport } as any)
const UpdatePasswordRoute = UpdatePasswordRouteImport.update({ id: '/update-password', path: '/update-password', getParentRoute: () => rootRouteImport } as any)

const SuperAdminIndexRoute = SuperAdminIndexRouteImport.update({
  id: '/super-admin/',
  path: '/super-admin/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/bills': typeof BillsRoute
  '/customers': typeof CustomersRoute
  '/login': typeof LoginRoute
  '/loss-analysis': typeof LossAnalysisRoute
  '/payments': typeof PaymentsRoute
  '/readings': typeof ReadingsRoute
  '/subscription': typeof SubscriptionRoute
  '/super-admin/': typeof SuperAdminIndexRoute
  '/account': typeof AccountRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/meters': typeof MetersRoute
  '/tariffs': typeof TariffsRoute
  '/update-password': typeof UpdatePasswordRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/bills': typeof BillsRoute
  '/customers': typeof CustomersRoute
  '/login': typeof LoginRoute
  '/loss-analysis': typeof LossAnalysisRoute
  '/payments': typeof PaymentsRoute
  '/readings': typeof ReadingsRoute
  '/subscription': typeof SubscriptionRoute
  '/super-admin': typeof SuperAdminIndexRoute
  '/account': typeof AccountRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/meters': typeof MetersRoute
  '/tariffs': typeof TariffsRoute
  '/update-password': typeof UpdatePasswordRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/bills': typeof BillsRoute
  '/customers': typeof CustomersRoute
  '/login': typeof LoginRoute
  '/loss-analysis': typeof LossAnalysisRoute
  '/payments': typeof PaymentsRoute
  '/readings': typeof ReadingsRoute
  '/subscription': typeof SubscriptionRoute
  '/super-admin/': typeof SuperAdminIndexRoute
  '/account': typeof AccountRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/meters': typeof MetersRoute
  '/tariffs': typeof TariffsRoute
  '/update-password': typeof UpdatePasswordRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistant'
    | '/bills'
    | '/customers'
    | '/login'
    | '/loss-analysis'
    | '/payments'
    | '/readings'
    | '/subscription'
    | '/super-admin/'
    | '/account'
    | '/forgot-password'
    | '/meters'
    | '/tariffs'
    | '/update-password'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistant'
    | '/bills'
    | '/customers'
    | '/login'
    | '/loss-analysis'
    | '/payments'
    | '/readings'
    | '/subscription'
    | '/super-admin'
    | '/account'
    | '/forgot-password'
    | '/meters'
    | '/tariffs'
    | '/update-password'
  id:
    | '__root__'
    | '/'
    | '/assistant'
    | '/bills'
    | '/customers'
    | '/login'
    | '/loss-analysis'
    | '/payments'
    | '/readings'
    | '/subscription'
    | '/super-admin/'
    | '/account'
    | '/forgot-password'
    | '/meters'
    | '/tariffs'
    | '/update-password'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistantRoute: typeof AssistantRoute
  BillsRoute: typeof BillsRoute
  CustomersRoute: typeof CustomersRoute
  LoginRoute: typeof LoginRoute
  LossAnalysisRoute: typeof LossAnalysisRoute
  PaymentsRoute: typeof PaymentsRoute
  ReadingsRoute: typeof ReadingsRoute
  SubscriptionRoute: typeof SubscriptionRoute
  SuperAdminIndexRoute: typeof SuperAdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/subscription': {
      id: '/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof SubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/readings': {
      id: '/readings'
      path: '/readings'
      fullPath: '/readings'
      preLoaderRoute: typeof ReadingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loss-analysis': {
      id: '/loss-analysis'
      path: '/loss-analysis'
      fullPath: '/loss-analysis'
      preLoaderRoute: typeof LossAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bills': {
      id: '/bills'
      path: '/bills'
      fullPath: '/bills'
      preLoaderRoute: typeof BillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/': {
      id: '/super-admin/'
      path: '/super-admin'
      fullPath: '/super-admin/'
      preLoaderRoute: typeof SuperAdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meters': {
      id: '/meters'
      path: '/meters'
      fullPath: '/meters'
      preLoaderRoute: typeof MetersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tariffs': {
      id: '/tariffs'
      path: '/tariffs'
      fullPath: '/tariffs'
      preLoaderRoute: typeof TariffsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/update-password': {
      id: '/update-password'
      path: '/update-password'
      fullPath: '/update-password'
      preLoaderRoute: typeof UpdatePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistantRoute: AssistantRoute,
  BillsRoute: BillsRoute,
  CustomersRoute: CustomersRoute,
  LoginRoute: LoginRoute,
  LossAnalysisRoute: LossAnalysisRoute,
  PaymentsRoute: PaymentsRoute,
  ReadingsRoute: ReadingsRoute,
  SubscriptionRoute: SubscriptionRoute,
  SuperAdminIndexRoute: SuperAdminIndexRoute,
  AccountRoute: AccountRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  MetersRoute: MetersRoute,
  TariffsRoute: TariffsRoute,
  UpdatePasswordRoute: UpdatePasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
