-- MIZAN multi-tenant project hierarchy and central oversight.
ALTER TABLE public.tenants ADD COLUMN IF NOT EXISTS tenant_type text NOT NULL DEFAULT 'project';
ALTER TABLE public.tenants ADD COLUMN IF NOT EXISTS parent_tenant_id uuid REFERENCES public.tenants(id) ON DELETE RESTRICT;
ALTER TABLE public.tenants DROP CONSTRAINT IF EXISTS tenants_tenant_type_check;
ALTER TABLE public.tenants ADD CONSTRAINT tenants_tenant_type_check CHECK (tenant_type IN ('project','central'));
CREATE INDEX IF NOT EXISTS tenants_parent_tenant_id_idx ON public.tenants(parent_tenant_id);

CREATE OR REPLACE FUNCTION public.central_tenant_id() RETURNS uuid LANGUAGE sql STABLE SECURITY DEFINER SET search_path = '' AS $$ SELECT id FROM public.tenants WHERE tenant_type='central' ORDER BY created_at,id LIMIT 1; $$;
REVOKE ALL ON FUNCTION public.central_tenant_id() FROM PUBLIC, anon; GRANT EXECUTE ON FUNCTION public.central_tenant_id() TO authenticated;

CREATE OR REPLACE FUNCTION public.create_project_tenant(_name text) RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path = '' AS $$ DECLARE v_id uuid; v_name text:=btrim(_name); v_central uuid; BEGIN IF auth.uid() IS NULL THEN RAISE EXCEPTION 'authentication required'; END IF; IF NOT public.is_super_admin() THEN RAISE EXCEPTION 'super admin required'; END IF; IF v_name='' THEN RAISE EXCEPTION 'tenant name required'; END IF; v_central:=public.central_tenant_id(); IF v_central IS NULL THEN RAISE EXCEPTION 'central tenant required'; END IF; INSERT INTO public.tenants(name,project_name,tenant_type,parent_tenant_id,subscription_status,subscription_expires_at) VALUES(v_name,v_name,'project',v_central,'active',now()+interval '365 days') RETURNING id INTO v_id; INSERT INTO public.audit_logs(tenant_id,user_id,action,entity,entity_id,meta) VALUES(v_id,auth.uid(),'tenant.created','tenant',v_id,jsonb_build_object('tenant_type','project','name',v_name)); RETURN v_id; END; $$;
REVOKE ALL ON FUNCTION public.create_project_tenant(text) FROM PUBLIC, anon; GRANT EXECUTE ON FUNCTION public.create_project_tenant(text) TO authenticated;

CREATE OR REPLACE FUNCTION public.create_central_tenant(_name text) RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path = '' AS $$ DECLARE v_id uuid; v_name text:=btrim(_name); BEGIN IF auth.uid() IS NULL THEN RAISE EXCEPTION 'authentication required'; END IF; IF NOT public.is_super_admin() THEN RAISE EXCEPTION 'super admin required'; END IF; IF v_name='' THEN RAISE EXCEPTION 'tenant name required'; END IF; IF EXISTS(SELECT 1 FROM public.tenants WHERE tenant_type='central') THEN RAISE EXCEPTION 'central tenant already exists'; END IF; INSERT INTO public.tenants(name,project_name,tenant_type,parent_tenant_id,subscription_status,subscription_expires_at) VALUES(v_name,v_name,'central',NULL,'active',now()+interval '3650 days') RETURNING id INTO v_id; INSERT INTO public.audit_logs(tenant_id,user_id,action,entity,entity_id,meta) VALUES(v_id,auth.uid(),'tenant.created','tenant',v_id,jsonb_build_object('tenant_type','central','name',v_name)); RETURN v_id; END; $$;
REVOKE ALL ON FUNCTION public.create_central_tenant(text) FROM PUBLIC, anon; GRANT EXECUTE ON FUNCTION public.create_central_tenant(text) TO authenticated;

CREATE OR REPLACE FUNCTION public.can_access_tenant(_tenant_id uuid) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = '' AS $$ SELECT public.is_super_admin() OR EXISTS(SELECT 1 FROM public.user_roles ur WHERE ur.user_id=auth.uid() AND (ur.tenant_id=_tenant_id OR ur.role='super_admin'::public.app_role)) OR EXISTS(SELECT 1 FROM public.user_roles ur JOIN public.tenants t ON t.id=ur.tenant_id WHERE ur.user_id=auth.uid() AND ur.role='manager'::public.app_role AND t.tenant_type='central' AND EXISTS(SELECT 1 FROM public.tenants child WHERE child.id=_tenant_id AND child.parent_tenant_id=t.id)); $$;
REVOKE ALL ON FUNCTION public.can_access_tenant(uuid) FROM PUBLIC, anon; GRANT EXECUTE ON FUNCTION public.can_access_tenant(uuid) TO authenticated;

CREATE OR REPLACE FUNCTION public.project_tenants() RETURNS SETOF public.tenants LANGUAGE sql STABLE SECURITY DEFINER SET search_path = '' AS $$ SELECT t.* FROM public.tenants t WHERE t.tenant_type='project' AND public.can_access_tenant(t.id) ORDER BY t.name; $$;
REVOKE ALL ON FUNCTION public.project_tenants() FROM PUBLIC, anon; GRANT EXECUTE ON FUNCTION public.project_tenants() TO authenticated;

CREATE OR REPLACE FUNCTION public.has_tenant_role(_tenant_id uuid,_role public.app_role) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = '' AS $$ SELECT EXISTS(SELECT 1 FROM public.user_roles WHERE user_id=auth.uid() AND role=_role AND (tenant_id=_tenant_id OR role='super_admin'::public.app_role OR (_role='manager'::public.app_role AND EXISTS(SELECT 1 FROM public.user_roles central_role JOIN public.tenants central_tenant ON central_tenant.id=central_role.tenant_id JOIN public.tenants target ON target.id=_tenant_id WHERE central_role.user_id=auth.uid() AND central_role.role='manager'::public.app_role AND central_tenant.tenant_type='central' AND target.parent_tenant_id=central_tenant.id)))); $$;
REVOKE ALL ON FUNCTION public.has_tenant_role(uuid,public.app_role) FROM PUBLIC, anon; GRANT EXECUTE ON FUNCTION public.has_tenant_role(uuid,public.app_role) TO authenticated;
